# Generated by Django 3.1.4 on 2020-12-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwblog', '0002_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=None),
        ),
    ]
