# Generated by Django 3.1.4 on 2020-12-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwblog', '0003_auto_20201230_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='edit_date',
        ),
    ]
