# Generated by Django 3.1.4 on 2020-12-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwblog', '0004_remove_article_edit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleeditor',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articleeditor',
            old_name='editor_id',
            new_name='editor',
        ),
    ]
