# Generated by Django 3.1.4 on 2020-12-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwblog', '0005_auto_20201230_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleEditor',
        ),
    ]
