# Generated by Django 3.1.4 on 2020-12-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwblog', '0006_delete_articleeditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwblog.article')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwblog.user')),
            ],
        ),
    ]
