# Generated by Django 3.1.5 on 2021-03-30 00:19

from django.db import migrations, models
import wwapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0002_category_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelocal',
            name='location',
            field=models.ImageField(upload_to=wwapp.models.ImageLocal.get_upload_path),
        ),
    ]
