# Generated by Django 3.1.7 on 2021-04-06 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wwapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwapp', '0002_category_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('image_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImgurImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wwapp.image')),
                ('imgur_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
            bases=('wwapp.image',),
        ),
        migrations.CreateModel(
            name='S3Image',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wwapp.image')),
                ('s3_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ImageField(upload_to=wwapp.models.S3Image.get_upload_path)),
            ],
            bases=('wwapp.image',),
        ),
    ]
