# Generated by Django 3.1.7 on 2021-04-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0003_auto_20210406_1450'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author_id', 'published', '-pub_date'], name='wwapp_artic_author__124596_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published', '-pub_date'], name='wwapp_artic_publish_88082a_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published', 'pub_date'], name='wwapp_artic_publish_7d57f5_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author_id', 'published', '-creation_date'], name='wwapp_artic_author__61eddd_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author_id', 'published', 'creation_date'], name='wwapp_artic_author__5f1232_idx'),
        ),
        migrations.AddIndex(
            model_name='articleversion',
            index=models.Index(fields=['article_id', 'version'], name='wwapp_artic_article_c3acbf_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_creator_id', 'category_type', 'category_name'], name='wwapp_categ_categor_06a7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_type', 'category_name'], name='wwapp_categ_categor_213194_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryitemassignation',
            index=models.Index(fields=['position'], name='wwapp_categ_positio_2fd119_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryitemassignation',
            index=models.Index(fields=['parent_category_id', 'position'], name='wwapp_categ_parent__cc7400_idx'),
        ),
    ]
