# Generated by Django 3.1.7 on 2021-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0004_auto_20210406_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgurimage',
            name='delete_hash',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='imgurimage',
            name='imgur_image_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
