# Generated by Django 3.2.4 on 2021-08-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0004_auto_20210507_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=45),
        ),
    ]
