# Generated by Django 3.2.4 on 2021-08-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0005_auto_20210414_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=45),
        ),
    ]
