# Generated by Django 3.1.5 on 2021-01-19 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=45)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleEditor',
            fields=[
                ('article_editor_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('article_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.IntegerField(default=1)),
                ('location', models.FileField(upload_to='posts/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45, unique=True)),
                ('category_type', models.CharField(choices=[('PROJECT', 'Project'), ('TOPIC', 'Topic'), ('SUBTOPIC', 'SubTopic')], default='PROJECT', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryEditor',
            fields=[
                ('category_editor_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='wwapp_user_usernam_75326a_idx'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='item_article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.article'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='item_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.category'),
        ),
        migrations.AddField(
            model_name='categoryeditor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.category'),
        ),
        migrations.AddField(
            model_name='categoryeditor',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wwapp.user'),
        ),
        migrations.AddField(
            model_name='articleversion',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.article'),
        ),
        migrations.AddField(
            model_name='articleeditor',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.article'),
        ),
        migrations.AddField(
            model_name='articleeditor',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.user'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wwapp.user'),
        ),
        migrations.AddConstraint(
            model_name='categoryeditor',
            constraint=models.UniqueConstraint(fields=('category', 'editor'), name='category_editor_unique'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_name'], name='wwapp_categ_categor_c92d4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='articleversion',
            constraint=models.UniqueConstraint(fields=('article', 'version'), name='article_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='articleeditor',
            constraint=models.UniqueConstraint(fields=('article', 'editor'), name='article_editor_unique'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_title'], name='wwapp_artic_article_419a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='wwapp_artic_author__2096fd_idx'),
        ),
    ]
