# Generated by Django 3.1.5 on 2021-01-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleversion',
            name='content',
        ),
    ]
