# Generated by Django 3.1.5 on 2021-01-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ImageField(upload_to='images/')),
                ('image_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('article_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.article')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.image')),
            ],
        ),
        migrations.AddConstraint(
            model_name='articleimage',
            constraint=models.UniqueConstraint(fields=('article', 'image'), name='article_image_unique'),
        ),
    ]
