# Generated by Django 3.1.4 on 2020-12-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_title'], name='wwapp_artic_article_419a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='wwapp_artic_author__2096fd_idx'),
        ),
    ]
