# Generated by Django 3.1.4 on 2021-01-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='wwapp_user_usernam_75326a_idx'),
        ),
    ]
