# Generated by Django 3.1.5 on 2021-02-01 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0002_remove_articleversion_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wwapp.article'),
        ),
    ]
