# Generated by Django 3.1.4 on 2021-01-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0002_auto_20210107_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45, unique=True)),
                ('category_type', models.CharField(choices=[('PROJECT', 'Project'), ('TOPIC', 'Topic'), ('SUBTOPIC', 'Sub-Topic')], default='PROJECT', max_length=45)),
                ('category_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wwapp.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_name'], name='wwapp_categ_categor_c92d4c_idx'),
        ),
    ]
