# Generated by Django 3.1.5 on 2021-01-21 06:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0002_auto_20210120_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_owner',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 6, 22, 12, 510327, tzinfo=utc), editable=False),
        ),
        migrations.CreateModel(
            name='ImageRemote',
            fields=[
                ('remote_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.URLField()),
                ('image_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLocal',
            fields=[
                ('local_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ImageField(upload_to='images/local/')),
                ('image_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='local_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.imagelocal'),
        ),
        migrations.AddField(
            model_name='image',
            name='remote_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.imageremote'),
        ),
    ]
