# Generated by Django 3.1.4 on 2020-12-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0002_auto_20201231_1109'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='wwapp_user_usernam_75326a_idx'),
        ),
    ]
