# Generated by Django 3.1.4 on 2021-01-01 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0003_auto_20201231_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45, unique=True)),
                ('category_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.user')),
                ('category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.category')),
            ],
        ),
    ]
