# Generated by Django 3.1.4 on 2021-01-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0003_auto_20210107_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(blank=True, default=None, max_length=45)),
                ('pub_date', models.DateTimeField(default=None)),
                ('published', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wwapp.user')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.category')),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_title'], name='wwapp_artic_article_419a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='wwapp_artic_author__2096fd_idx'),
        ),
    ]
