# Generated by Django 3.1.5 on 2021-02-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0003_article_article_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleversion',
            name='hidden_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
