# Generated by Django 3.1.4 on 2021-01-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleEditor',
        ),
    ]
