# Generated by Django 3.1.5 on 2021-01-23 04:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0004_auto_20210122_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 4, 20, 35, 755978, tzinfo=utc), editable=False),
        ),
    ]
