# Generated by Django 3.1.4 on 2021-01-01 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0005_delete_articleeditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.article')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='articleeditor',
            constraint=models.UniqueConstraint(fields=('article', 'editor'), name='article_editor_unique'),
        ),
    ]
