# Generated by Django 3.1.4 on 2021-01-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0006_auto_20210107_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_article_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.article')),
                ('item_category_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.category')),
            ],
        ),
    ]
