# Generated by Django 3.1.4 on 2021-01-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0006_auto_20210101_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_parent',
        ),
    ]
