# Generated by Django 3.1.4 on 2021-01-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0007_remove_category_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.category'),
        ),
    ]
