# Generated by Django 3.1.4 on 2021-01-04 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0008_category_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_article_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.article')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_parent',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(default='ROOT', max_length=45),
        ),
        migrations.CreateModel(
            name='CategoryItemAssignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.categoryitem')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='item_category_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwapp.category'),
        ),
        migrations.AddConstraint(
            model_name='categoryitemassignation',
            constraint=models.UniqueConstraint(fields=('item', 'parent_category'), name='category_item_unique'),
        ),
    ]
