# Generated by Django 3.1.4 on 2021-01-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0009_auto_20210105_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleeditor',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleeditor',
            name='editor',
        ),
        migrations.RemoveConstraint(
            model_name='categoryitemassignation',
            name='category_item_unique',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='wwapp.category'),
        ),
        migrations.AlterField(
            model_name='categoryitemassignation',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wwapp.categoryitem'),
        ),
        migrations.AddConstraint(
            model_name='categoryitemassignation',
            constraint=models.UniqueConstraint(fields=('item', 'position'), name='category_item_unique'),
        ),
        migrations.DeleteModel(
            name='ArticleEditor',
        ),
    ]
