# Generated by Django 3.1.4 on 2021-01-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0009_auto_20210107_0207'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articleeditor',
            constraint=models.UniqueConstraint(fields=('article', 'editor'), name='article_editor_unique'),
        ),
    ]
