# Generated by Django 3.1.4 on 2021-01-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0010_auto_20210107_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
