# Generated by Django 3.1.4 on 2021-01-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0011_auto_20210105_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryItemAssignation',
        ),
    ]
