# Generated by Django 3.1.4 on 2021-01-05 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0012_delete_categoryitemassignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItemAssignation',
            fields=[
                ('item_assignation_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wwapp.categoryitem')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwapp.category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categoryitemassignation',
            constraint=models.UniqueConstraint(fields=('item', 'position'), name='category_item_unique'),
        ),
    ]
