# Generated by Django 3.1.4 on 2021-01-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0012_remove_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryitem',
            old_name='item_article_id',
            new_name='item_article',
        ),
        migrations.RenameField(
            model_name='categoryitem',
            old_name='item_category_id',
            new_name='item_category',
        ),
    ]
