# Generated by Django 3.1.4 on 2021-01-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0013_auto_20210107_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryitemassignation',
            name='parent_category',
        ),
    ]
