# Generated by Django 3.1.4 on 2021-01-08 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wwapp', '0014_remove_categoryitemassignation_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitemassignation',
            name='parent_category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='wwapp.category'),
            preserve_default=False,
        ),
    ]
